### ISSUE TITLE
Support identifiers for attributes

### ISSUE THREAD

**Issue by webignition** [webignition/bas-spec#232]
Need to be able to identify an attribute of an element as assertions may be performed against actions e.g. `$this->assertEquals($element->getAttribute('title'), "foo");`

**Comment by webignition** [comment]
Initial thought is to use the colon to separate selector from attribute:

`.input:title`

However the colon is currently used to separate a selector from the position within a node list:

`.input:2`

Can we change the syntax for the position?

**Comment by webignition** [comment]
Listing out some identifiers where the attribute is tagged on at the end after a colon:

```
".selector":attribute_name
".listed-item":0:attribute_name
"//foo":attribute_name
"/foo":1:attribute_name
page_import_name.elements.foo:attribute_name
elements.element_name:attribute_name
```

**Comment by webignition** [comment]
Nope, a colon as a separator is going to be confusing if parseable.

Page and browser object properties are dot-separated:

```
$page.title
$page.url
$browser.size
```

**Comment by webignition** [comment]
Listing out some identifiers where the attribute is dot-separated:

```
".selector".attribute_name
".listed-item":0.attribute_name
"//foo".attribute_name
"/foo":1.attribute_name
page_import_name.elements.foo.attribute_name
elements.element_name.attribute_name
```

**Comment by webignition** [comment]
Dot separation seems odd when used next to CSS selectors ...

**Comment by webignition** [comment]
Actually, not so much odd since the CSS selector (or XPath expression) is wrapped in quotes.

**Comment by webignition** [comment]
**Simple test example**

```yaml
config:
    url: http://example.com/

step_name:
    actions:
     - 'click ".button"'
    assertions:
     - '".element".title is "title value"'
```

**Comment by webignition** [comment]
**Page model with direct in-test usage example**

```yaml
# page.yml
url: "https://www.google.com"
elements:
  button: '".button"'
  heading: '".heading"'
```
```yaml
# test.yml
config:
  browser: chrome
  url: http://example.com/

imports:
  pages:
    page_import_name: "./page.yml"

step_name:
  actions:
   - 'click ".button"'

  assertions:
   - 'page_import_name.heading.title is "title value"'
  
```

**Comment by webignition** [comment]
**Page model with imported step usage example**

```yaml
# page.yml
url: "https://www.google.com"
elements:
  button: '".button"'
  heading: '".heading"'
```
```yaml
# step.yml
actions:
 - 'click ".button"'

assertions:
 - '$elements.heading.title is "title value"'
```
```yaml
# test.yml
config:
  browser: chrome
  url: http://example.com/

imports:
  steps:
    step_import_name: "./step.yml"
  pages:
    page_import_name: "./page.yml"

step_name:
  use: step_import_name
  elements:
    heading: page_import_name.elements.heading

  
```
